name: Build and Release

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
    
    - name: Install dependencies
      run: |
        sudo dnf install -y rpm zip gcc make docker rpm-build
    
    - name: Build RPM
      run: |
        cd c
        # Create the source tarball
        mkdir -p wizardscastle-1.0
        cp *.c wizardscastle-1.0/
        cp *.h wizardscastle-1.0/
        cp Makefile wizardscastle-1.0/
        tar -czf wizardscastle-1.0.tar.gz wizardscastle-1.0
        rm -rf wizardscastle-1.0
        # Move the source tarball to the SOURCES directory for rpmbuild
        mkdir -p ~/rpmbuild/SOURCES
        cp wizardscastle-1.0.tar.gz ~/rpmbuild/SOURCES/
        # Build the RPM using the existing spec file
        rpmbuild -ba -D 'debug_package %{nil}' wizardscastle.spec
    
    - name: Build Windows version
      run: |
        cd c
        # Debug: Print current directory and list files
        pwd
        ls -la
        # Ensure the Docker command mounts the current directory correctly
        docker run --rm -v $(pwd):/src -w /src mdashnet/mingw:latest /bin/sh -c "ls -la && x86_64-w64-mingw32-gcc main.c wizards-castle.c -o wizard_windows.exe"
        # Debug: Check if the Windows executable was created
        ls -la
    
    - name: Build MS-DOS version
      run: |
        cd c
        make msdos
    
    - name: Build Linux version and create package
      run: |
        cd c
        make
        mkdir -p wizardscastle-linux
        cp wizardscastle wizardscastle-linux/
        tar -czf wizardscastle-linux.tar.gz wizardscastle-linux
        rm -rf wizardscastle-linux
    
    - name: Create DOS zip package
      run: |
        mkdir -p dos_package
        cp c/wizard.exe dos_package/
        cp c/CWSDPMI.EXE dos_package/
        cd dos_package
        zip -r ../wizard.zip .
        cd ..
    
    - name: Generate release date
      id: date
      run: echo "::set-output name=date::v$(date +'%Y%m%d')"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.date.outputs.date }}
        release_name: Release ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
    
    - name: Upload RPM Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ~/rpmbuild/RPMS/x86_64/wizardscastle-1.0-1.x86_64.rpm
        asset_name: wizardscastle-${{ steps.date.outputs.date }}.rpm
        asset_content_type: application/x-rpm
    
    - name: Upload Windows Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./c/wizard_windows.exe
        asset_name: wizardscastle-${{ steps.date.outputs.date }}-windows.exe
        asset_content_type: application/octet-stream
    
    - name: Upload DOS Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./wizard.zip
        asset_name: wizardscastle-${{ steps.date.outputs.date }}-dos.zip
        asset_content_type: application/zip
    
    - name: Upload Linux Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./c/wizardscastle-linux.tar.gz
        asset_name: wizardscastle-${{ steps.date.outputs.date }}-linux.tar.gz
        asset_content_type: application/gzip
