name: Build and Release

on:
  push:
    branches:
      - main  # or your default branch name
  schedule:
    - cron: '0 0 1 */1 *'  # Runs at 00:00 on the 1st of every month

env:
  BUILD_CONFIGURATION: Release
  QT_VERSION: '5.15.2'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      date: ${{ steps.date.outputs.date }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
    
    - name: Install dependencies
      run: |
        sudo dnf install -y rpm zip gcc make rpm-build mingw64-gcc wget qt6-qtbase-devel

    - name: Build RPM
      run: |
        pushd c
        mkdir -p wizardscastle-1.0
        cp *.c   wizardscastle-1.0/
        cp *.h   wizardscastle-1.0/
        cp *.pro wizardscastle-1.0/
        cp *.cpp wizardscastle-1.0/
        cp Makefile wizardscastle-1.0/
        tar -czf wizardscastle-1.0.tar.gz wizardscastle-1.0
        rm -rf wizardscastle-1.0
        mkdir -p ~/rpmbuild/SOURCES
        cp wizardscastle-1.0.tar.gz ~/rpmbuild/SOURCES/
        rpmbuild -ba -D 'debug_package %{nil}' wizardscastle.spec
        popd

    - name: Build Windows version
      run: |
        pushd c
        x86_64-w64-mingw32-gcc *.c -o wizard_windows.exe
        echo "Checking if executable was created:"
        ls -l wizard_windows.exe
        ls -l *.exe
        popd

    - name: Build MS-DOS version
      run: |
        wget https://github.com/andrewwutw/build-djgpp/releases/download/v3.3/djgpp-linux64-gcc1210.tar.bz2
        tar -xf djgpp-linux64-gcc1210.tar.bz2 -C /usr/local/
        export PATH=$PATH:/usr/local/djgpp/bin
        pushd c
        /usr/local/djgpp/bin/i586-pc-msdosdjgpp-gcc *.c -o wizard.exe
        wget http://na.mirror.garr.it/mirrors/djgpp/current/v2misc/csdpmi7b.zip
        unzip -u csdpmi7b.zip
        find * -type f
        cp bin/CWSDPMI.EXE cwsdpmi.exe
        popd 

    - name: Build Linux version and create package
      run: |
        pushd c
        make
        mkdir -p wizardscastle-linux
        cp wizardscastle      wizardscastle-linux/
        tar -czf wizardscastle-linux.tar.gz wizardscastle-linux
        rm -rf wizardscastle-linux
        popd

    - name: Create DOS zip package
      run: |
        mkdir -p dos_package
        cp c/wizard.exe dos_package/
        cp c/cwsdpmi.exe dos_package/
        pushd dos_package
        zip -r ../wizard.zip .
        popd

    - name: Find RPM Package
      id: find_rpm
      run: |
        RPM_PATH=$(find ~/rpmbuild/RPMS/x86_64/ -name "wizardscastle-*.rpm" | head -n 1)
        if [ -z "$RPM_PATH" ]; then
          echo "Error: RPM file not found"
          exit 1
        fi
        RPM_FILENAME=$(basename "$RPM_PATH")
        echo "rpm_path=$RPM_PATH" >> $GITHUB_OUTPUT
        echo "rpm_filename=$RPM_FILENAME" >> $GITHUB_OUTPUT
    
    - name: Generate release date and unique identifier
      id: date
      run: |
        echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        echo "unique_id=$(date +'%H%M%S')" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.date.outputs.date }}-${{ steps.date.outputs.unique_id }}
        release_name: Release ${{ steps.date.outputs.date }}-${{ steps.date.outputs.unique_id }}
        draft: false
        prerelease: false

    - name: Upload RPM Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.find_rpm.outputs.rpm_path }}
        asset_name: ${{ steps.find_rpm.outputs.rpm_filename }}
        asset_content_type: application/x-rpm
    
    - name: Upload Windows Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./c/wizard_windows.exe
        asset_name: wizardscastle-${{ steps.date.outputs.date }}-windows.exe
        asset_content_type: application/octet-stream
    
    - name: Upload DOS Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./wizard.zip
        asset_name: wizardscastle-${{ steps.date.outputs.date }}-dos.zip
        asset_content_type: application/zip
    
    - name: Upload Linux Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./c/wizardscastle-linux.tar.gz
        asset_name: wizardscastle-${{ steps.date.outputs.date }}-linux.tar.gz
        asset_content_type: application/gzip

  build-qt-windows:
    runs-on: windows-latest
    needs: build-and-release
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        dir: ${{ runner.temp }}
        cache: true
        setup-python: false

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        toolset: 14.29
        spectre: false

    - name: Build Qt application
      shell: cmd
      working-directory: c
      run: |
        echo Current directory: %CD%
        set CL=/MD /O1 /W1 /wd4996 /wd4244 /wd5105 /Zc:preprocessor- /GS- /D_CRT_SECURE_NO_WARNINGS /diagnostics:column /errorReport:send
        qmake wizard_castle_qt5.pro
        nmake

    - name: Package Qt artifacts
      shell: cmd
      run: |
        mkdir win_package
        if exist c\release\wizardscastle-qt.exe (
          copy c\release\wizardscastle-qt.exe win_package\
          windeployqt --release --no-translations --no-system-d3d-compiler win_package\wizardscastle-qt.exe
        ) else if exist c\wizardscastle-qt.exe (
          copy c\wizardscastle-qt.exe win_package\
          windeployqt --release --no-translations --no-system-d3d-compiler win_package\wizardscastle-qt.exe
        ) else (
          echo No exe found
          exit 1
        )
        powershell Compress-Archive -Path win_package\* -DestinationPath wizards_castle_qt_windows.zip

    - name: Upload Qt Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build-and-release.outputs.upload_url }}
        asset_path: ./wizards_castle_qt_windows.zip
        asset_name: wizardscastle-${{ needs.build-and-release.outputs.date }}-qt-windows.zip
        asset_content_type: application/zip

  # I don't actually have a MAC to test this
  build-qt-macos:
    runs-on: macos-latest
    needs: build-and-release
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        dir: ${{ runner.temp }}
        cache: true
        setup-python: false

    - name: Install additional dependencies
      run: |
        brew install cmake

    - name: Build Qt application
      working-directory: c
      run: |
        # Print Qt information for debugging
        echo "Qt installation path: $Qt5_DIR"
        echo "QTDIR: $QTDIR"
        echo "Using qmake from: $(which qmake)"
        
        # Build the application
        qmake wizard_castle_qt5.pro
        make -j$(sysctl -n hw.ncpu)

    - name: Create app bundle and DMG
      working-directory: c
      run: |
        # Debug - show us where everything is
        echo "Current directory contents:"
        ls -R
        
        # Create the app bundle structure
        mkdir -p WizardsCastle.app/Contents/{MacOS,Resources,Frameworks}
        
        # Look for the executable in multiple possible locations
        if [ -f "wizardscastle-qt.app/Contents/MacOS/wizardscastle-qt" ]; then
          cp wizardscastle-qt.app/Contents/MacOS/wizardscastle-qt WizardsCastle.app/Contents/MacOS/
        elif [ -f "release/wizardscastle-qt" ]; then
          cp release/wizardscastle-qt WizardsCastle.app/Contents/MacOS/
        elif [ -f "wizardscastle-qt" ]; then
          cp wizardscastle-qt WizardsCastle.app/Contents/MacOS/
        else
          echo "Error: Could not find executable. Directory contents:"
          find . -type f -name "wizardscastle*"
          exit 1
        fi
        
        # Create Info.plist
        cat > WizardsCastle.app/Contents/Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>wizardscastle-qt</string>
            <key>CFBundleIconFile</key>
            <string>wizardscastle.icns</string>
            <key>CFBundleIdentifier</key>
            <string>com.wizardscastle.app</string>
            <key>CFBundleName</key>
            <string>Wizard's Castle</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>LSMinimumSystemVersion</key>
            <string>10.13</string>
            <key>NSHighResolutionCapable</key>
            <true/>
        </dict>
        </plist>
        EOF
        
        # Use macdeployqt to create DMG
        macdeployqt WizardsCastle.app -dmg -verbose=2 

    - name: Upload macOS Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build-and-release.outputs.upload_url }}
        asset_path: ./c/WizardsCastle.dmg
        asset_name: wizardscastle-${{ needs.build-and-release.outputs.date }}-qt-macos.dmg
        asset_content_type: application/x-apple-diskimage

  build-qt-windows-msi:
    runs-on: windows-latest
    needs: build-and-release
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        dir: ${{ runner.temp }}
        cache: true
        setup-python: false

    - name: Setup WiX Toolset
      run: |
        mkdir -p ${{ runner.temp }}/wix
        Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip" -OutFile "${{ runner.temp }}/wix.zip"
        Expand-Archive -Path "${{ runner.temp }}/wix.zip" -DestinationPath "${{ runner.temp }}/wix"
        echo "${{ runner.temp }}/wix" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        toolset: 14.29
        spectre: false

    - name: Build Qt application
      shell: cmd
      working-directory: c
      run: |
        echo Current directory: %CD%
        set CL=/MD /O1 /W1 /wd4996 /wd4244 /wd5105 /Zc:preprocessor- /GS- /D_CRT_SECURE_NO_WARNINGS /diagnostics:column /errorReport:send
        qmake wizard_castle_qt5.pro
        nmake

    - name: Create deployment directory
      shell: cmd
      run: |
        mkdir deploy
        if exist c\release\wizardscastle-qt.exe (
          copy c\release\wizardscastle-qt.exe deploy\
          windeployqt --release --no-translations --no-system-d3d-compiler deploy\wizardscastle-qt.exe
        ) else if exist c\wizardscastle-qt.exe (
          copy c\wizardscastle-qt.exe deploy\
          windeployqt --release --no-translations --no-system-d3d-compiler deploy\wizardscastle-qt.exe
        )



    - name: Get version info
      id: version
      shell: bash
      run: |
        # Get year, month, day from the last commit
        YEAR=$(git log -1 --format=%cd --date=format:%y -- c/)
        MONTH=$(git log -1 --format=%cd --date=format:%m -- c/)
        DAY=$(git log -1 --format=%cd --date=format:%d -- c/)
        # Remove leading zeros to ensure valid integer format
        MONTH=$(echo $MONTH | sed 's/^0*//')
        DAY=$(echo $DAY | sed 's/^0*//')
        # Format as version string
        COMMIT_DATE="${YEAR}.${MONTH}.${DAY}"
        echo "commit_date=${COMMIT_DATE}" >> $GITHUB_OUTPUT
        # Also get the commit SHA for the filename
        #COMMIT_SHA=$(git log -1 --format=%h -- c/)
        #echo "commit_sha=${COMMIT_SHA}" >> $GITHUB_OUTPUT

    - name: Create WiX config
      shell: pwsh
      env:
        COMMIT_DATE: ${{ steps.version.outputs.commit_date }}
      run: |
        echo ^<?xml version="1.0" encoding="UTF-8"?^> > installer.wxs
        echo ^<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"^> >> installer.wxs
        echo   ^<Product Id="*" Name="Wizard's Castle" Language="1033" Version="%COMMIT_DATE%" Manufacturer="Jason Hall" UpgradeCode="e27db2c8-b1b6-4cfa-a8f0-97e6dcf0a0e0"^> >> installer.wxs
        echo     ^<Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" /^> >> installer.wxs
        echo     ^<MajorUpgrade DowngradeErrorMessage="A newer version is already installed." /^> >> installer.wxs
        echo     ^<MediaTemplate EmbedCab="yes" /^> >> installer.wxs
        echo     ^<Icon Id="icon.ico" SourceFile="c\icon.ico"/^> >> installer.wxs
        echo     ^<Property Id="ARPPRODUCTICON" Value="icon.ico" /^> >> installer.wxs
        echo     ^<Directory Id="TARGETDIR" Name="SourceDir"^> >> installer.wxs
        echo       ^<Directory Id="ProgramFilesFolder"^> >> installer.wxs
        echo         ^<Directory Id="INSTALLFOLDER" Name="WizardsCastle"^> >> installer.wxs
        echo           ^<!-- Main application files --^> >> installer.wxs
        echo           ^<Component Id="MainExecutable" Guid="*"^> >> installer.wxs
        echo             ^<File Id="WizardsCastleEXE" Source="deploy\wizardscastle-qt.exe" KeyPath="yes"^> >> installer.wxs
        echo               ^<Shortcut Id="startmenuShortcut" Directory="ProgramMenuDir" Name="Wizard's Castle" WorkingDirectory="INSTALLFOLDER" Icon="icon.ico" IconIndex="0" Advertise="yes" /^> >> installer.wxs
        echo               ^<Shortcut Id="desktopShortcut" Directory="DesktopFolder" Name="Wizard's Castle" WorkingDirectory="INSTALLFOLDER" Icon="icon.ico" IconIndex="0" Advertise="yes" /^> >> installer.wxs
        echo             ^</File^> >> installer.wxs
        echo           ^</Component^> >> installer.wxs
        echo           ^<!-- Qt and dependency files --^> >> installer.wxs
        echo           ^<Component Id="QtDependencies" Guid="*"^> >> installer.wxs
        echo             ^<File Id="Qt5Core" Source="deploy\Qt5Core.dll" /^> >> installer.wxs
        echo             ^<File Id="Qt5Gui" Source="deploy\Qt5Gui.dll" /^> >> installer.wxs
        echo             ^<File Id="Qt5Widgets" Source="deploy\Qt5Widgets.dll" /^> >> installer.wxs
        echo           ^</Component^> >> installer.wxs
        echo           ^<!-- Platform plugins --^> >> installer.wxs
        echo           ^<Directory Id="platforms" Name="platforms"^> >> installer.wxs
        echo             ^<Component Id="QtPlatforms" Guid="*"^> >> installer.wxs
        echo               ^<File Id="qwindows" Source="deploy\platforms\qwindows.dll" /^> >> installer.wxs
        echo             ^</Component^> >> installer.wxs
        echo           ^</Directory^> >> installer.wxs
        echo           ^<!-- Styles plugins if used --^> >> installer.wxs
        echo           ^<Directory Id="styles" Name="styles"^> >> installer.wxs
        echo             ^<Component Id="QtStyles" Guid="*"^> >> installer.wxs
        echo               ^<File Id="qwindowsvistastyle" Source="deploy\styles\qwindowsvistastyle.dll" /^> >> installer.wxs
        echo             ^</Component^> >> installer.wxs
        echo           ^</Directory^> >> installer.wxs
        echo         ^</Directory^> >> installer.wxs
        echo       ^</Directory^> >> installer.wxs
        echo       ^<Directory Id="ProgramMenuFolder"^> >> installer.wxs
        echo         ^<Directory Id="ProgramMenuDir" Name="Wizard's Castle"^> >> installer.wxs
        echo           ^<Component Id="ProgramMenuDir" Guid="*"^> >> installer.wxs
        echo             ^<RemoveFolder Id="ProgramMenuDir" On="uninstall" /^> >> installer.wxs
        echo             ^<RegistryValue Root="HKCU" Key="Software\WizardsCastle" Type="string" Value="" KeyPath="yes" /^> >> installer.wxs
        echo           ^</Component^> >> installer.wxs
        echo         ^</Directory^> >> installer.wxs
        echo       ^</Directory^> >> installer.wxs
        echo       ^<Directory Id="DesktopFolder" Name="Desktop" /^> >> installer.wxs
        echo     ^</Directory^> >> installer.wxs
        echo     ^<Feature Id="ProductFeature" Title="WizardsCastle" Level="1"^> >> installer.wxs
        echo       ^<ComponentRef Id="MainExecutable" /^> >> installer.wxs
        echo       ^<ComponentRef Id="QtDependencies" /^> >> installer.wxs
        echo       ^<ComponentRef Id="QtPlatforms" /^> >> installer.wxs
        echo       ^<ComponentRef Id="QtStyles" /^> >> installer.wxs
        echo       ^<ComponentRef Id="ProgramMenuDir" /^> >> installer.wxs
        echo     ^</Feature^> >> installer.wxs
        echo   ^</Product^> >> installer.wxs
        echo ^</Wix^> >> installer.wxs

    - name: Build MSI
      shell: cmd
      run: |
        candle installer.wxs
        light -ext WixUIExtension installer.wixobj

    - name: Upload MSI Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build-and-release.outputs.upload_url }}
        asset_path: ./installer.msi
        asset_name: wizardscastle-${{ needs.build-and-release.outputs.date }}-qt-windows.msi
        asset_content_type: application/x-msi
