name: Qt5 MSVC Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_CONFIGURATION: Release
  QT_VERSION: '5.15.2'
  CL_MPcount: 1
  MAKEFLAGS: -j1
  MSBUILDDISABLENODEREUSE: 1

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        dir: ${{ runner.temp }}
        cache: true
        setup-python: false

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        toolset: 14.29
        spectre: false

    - name: Create build directory
      shell: cmd
      run: mkdir "%RUNNER_TEMP%\build"

    - name: Set Qt Environment Variables
      shell: bash
      run: |
        echo "QTDIR=${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/msvc2019_64" >> $GITHUB_ENV
        echo "QtToolsPath=${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/msvc2019_64/bin" >> $GITHUB_ENV

    - name: Build application
      shell: cmd
      working-directory: c
      run: |
        echo Current directory: %CD%
        
        REM Set compiler flags
        set CL=/MP1 /Zm200 /FS
        
        REM Configure and build
        qmake -o Makefile.win wizard_castle_qt5.pro CONFIG+=debug_and_release
        if %ERRORLEVEL% NEQ 0 (
          echo qmake failed
          exit /b %ERRORLEVEL%
        )
        
        nmake -f Makefile.win
        if %ERRORLEVEL% NEQ 0 (
          echo Build failed
          exit /b %ERRORLEVEL%
        )

    - name: Run windeployqt
      shell: cmd
      working-directory: c
      run: |
        "%QtToolsPath%\windeployqt.exe" --release wizards_castle_qt5.exe

    - name: Package application
      shell: cmd
      run: |
        mkdir win_package
        move c\wizards_castle_qt5.exe win_package\
        move c\*.dll win_package\
        move c\platforms win_package\
        move c\styles win_package\
        powershell Compress-Archive -Path win_package -DestinationPath wizards_castle_windows.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Wizards-Castle-Windows
        path: wizards_castle_windows.zip
