name: Qt5 MSVC Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_CONFIGURATION: Release
  QT_VERSION: '5.15.2'
  VSVERSION: '2022'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[17.0,18.0)'
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        dir: ${{ runner.temp }}
        cache: true
        setup-python: false

    - name: Setup Visual Studio Environment
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set >> %GITHUB_ENV%

    - name: Verify Visual Studio Setup
      shell: cmd
      run: |
        where cl.exe
        where nmake.exe
        cl.exe /? > nul
        if errorlevel 1 (
          echo CL.exe not working properly
          exit /b 1
        )
        nmake /? > nul
        if errorlevel 1 (
          echo NMAKE.exe not working properly
          exit /b 1
        )

    - name: Set Qt Environment Variables
      shell: cmd
      run: |
        echo QTDIR=%RUNNER_TEMP%\Qt\%QT_VERSION%\msvc2019_64>> %GITHUB_ENV%
        echo QtToolsPath=%RUNNER_TEMP%\Qt\%QT_VERSION%\msvc2019_64\bin>> %GITHUB_ENV%
        
    - name: Create build directory
      shell: cmd
      run: |
        mkdir build
        cd build

    - name: Build application
      shell: cmd
      working-directory: c
      run: |
        echo Current directory: %CD%
        
        REM Ensure we're using the right compiler
        where cl.exe
        
        REM Configure with qmake
        qmake -v
        qmake wizard_castle_qt5.pro -spec win32-msvc "CONFIG+=release"
        if errorlevel 1 (
          echo qmake failed
          exit /b 1
        )
        
        REM Build with nmake
        echo Running nmake...
        nmake /NOLOGO
        if errorlevel 1 (
          echo nmake failed with error level %ERRORLEVEL%
          dir /s /b
          exit /b 1
        )

    - name: Run windeployqt
      shell: cmd
      working-directory: c
      run: |
        "%QtToolsPath%\windeployqt.exe" --release wizards_castle_qt5.exe

    - name: Package application
      shell: cmd
      run: |
        mkdir win_package
        move c\wizards_castle_qt5.exe win_package\
        move c\*.dll win_package\
        move c\platforms win_package\
        move c\styles win_package\
        powershell Compress-Archive -Path win_package -DestinationPath wizards_castle_windows.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Wizards-Castle-Windows
        path: wizards_castle_windows.zip
