name: Qt5 MSVC Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_CONFIGURATION: Release
  QT_VERSION: '5.15.2'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[17.0,18.0)'

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        dir: ${{ runner.temp }}
        cache: true
        setup-python: false

    - name: Setup Visual Studio Environment
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set > %GITHUB_ENV%
        where cl.exe
        cl.exe /? > nul

    - name: Verify Environment
      shell: cmd
      run: |
        echo PATH=%PATH%
        echo INCLUDE=%INCLUDE%
        echo LIB=%LIB%
        where cl.exe
        where nmake.exe
        where qmake.exe

    - name: Build application
      shell: cmd
      working-directory: c
      run: |
        echo Current directory: %CD%
        dir
        
        REM Verify compiler access
        echo Testing cl.exe...
        where cl.exe
        
        REM Run qmake with full path and debug output
        echo Running qmake...
        "%QtToolsPath%\qmake.exe" -d wizard_castle_qt5.pro -spec win32-msvc "CONFIG+=debug"
        if errorlevel 1 (
          echo qmake failed
          type qmake.log
          exit /b 1
        )
        
        REM Build with nmake
        echo Running nmake...
        nmake /NOLOGO
        if errorlevel 1 (
          echo nmake failed
          type error.log
          exit /b 1
        )

    - name: Run windeployqt
      shell: cmd
      working-directory: c
      run: |
        "%QtToolsPath%\windeployqt.exe" --debug wizards_castle_qt5.exe

    - name: Package application
      shell: cmd
      run: |
        mkdir win_package
        move c\wizards_castle_qt5.exe win_package\
        move c\*.dll win_package\
        move c\platforms win_package\
        move c\styles win_package\
        powershell Compress-Archive -Path win_package -DestinationPath wizards_castle_windows.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Wizards-Castle-Windows
        path: wizards_castle_windows.zip
