name: Qt5 MSVC Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      CL: /MP    # Enable parallel compilation
      _CL_: /MP  # Additional flag for cl.exe
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        tools: 'tools_qtcreator'
        cache: true

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        sdk: '10.0.20348.0'
        toolset: '14.29'
        vsversion: '2022'

    - name: Build application
      shell: cmd
      run: |
        cd c
        qmake -o Makefile wizard_castle_qt5.pro
        set CL=/MP
        jom

    - name: Run windeployqt
      run: |
        cd c
        windeployqt.exe wizards_castle_qt5.exe

    - name: Package application
      run: |
        mkdir win_package
        move c\wizards_castle_qt5.exe win_package\
        move c\*.dll win_package\
        move c\platforms win_package\
        move c\styles win_package\
        Compress-Archive -Path win_package -DestinationPath wizards_castle_windows.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Wizards-Castle-Windows
        path: wizards_castle_windows.zip
